title: Pirate's Life
description: >-
  A wannabe hacker's corner of the web.
author:
  By Ad0n

social:
  name: Ad0n
  - title: GitHub aka. a repository of unfinished projects
    icon: github
    url: "https://github.com/Dogru-Isim/"
  - title: HackTheBox
    icon: hackthebox
    url: "https://app.hackthebox.com/users/535825"

theme: minima

url: "https://dogru-isim.github.io"
baseurl: ""

minima:
    skin: dark       # auto | classic | dark | solarized
