title: Pirate's Life

author:
   name: By Ad0n

description: >
  A wannabe hacker's diary.

social:
  name: Ad0n
  links:
    - https://github.com/Dogru-Isim/
    - https://app.hackthebox.com/users/535825

remote_theme: jekyll/minima

# Minima requires the following plugins:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

url: "https://dogru-isim.github.io"
baseurl: ""

minima:
   skin: auto
   #     * classic            Default, light color scheme.
   #     * dark               Dark variant of the classic skin.
   #     * auto               Adaptive skin based on the classic and dark skins.
   #     * solarized-light    Light variant of solarized color scheme.
   #     * solarized-dark     Dark variant of solarized color scheme.
   #     * solarized          Adaptive skin for solarized color scheme skins.
