title: Pirate's Life
description: >-
  A wannabe hacker's diary.

author:
  By Ad0n

social:
  name: Ad0n
  links:
    - https://github.com/Dogru-Isim/
    - https://app.hackthebox.com/users/535825

remote_theme: jekyll/minima

# Minima requires the following plugins:
plugins:
  - jekyll-feed
  - jekyll-seo-tag

url: "https://dogru-isim.github.io"
baseurl: ""

minima:
    skin: auto       # auto | classic | dark | solarized
