#remote_theme: "jekyll/minima@1e8a445"
theme: minima
title: My Awesome Site

title: A Cyber Security Enthusiast's Corner
description: >-
  A cyber security enthusiast's corner of the web where he shares his experiences and thoughts.
author:
  name: Ad0n

theme: minima

url: "https://dogru-isim.github.io"
baseurl: ""

minima:
skin: dark        # auto | classic | dark | solarized
social_links:
  github: https://github.com/Dogru-Isim/
  hackthebox: https://app.hackthebox.com/users/535825
